spring:
  data:
    mongodb:
      database: intercompany
      authentication-database: admin
      host: 172.16.213.40
      port: 9001
      username: root
      password: C1gr4.2o24.T3kN0s!

bitone:
  integration:
    api-key: "d896c408-9f6c-45b7-8ef1-59c323dd67f8"
    url: "https://bit-one-tools.ar/services/api/external-batch-process/register"