server:
  port:
    8095
spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
sap:
  edelflex:
    url: https://10.250.2.10:50000/b1s/v1/
    credentials:
      user: gregorio.hakimian
      password: EDFsapbone
      company: SBOEDEL24TST

sqlserver:
  jdbcUrl: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=master
  username: sa
  password: LongPassword123
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

team-center:
  querys:
    schema: DB_Edelflex_SAP
    acce-inline:
      group-code: 1
      get: SELECT FIELDS FROM ${team-center.querys.schema}.dbo.AcceInline WHERE Status IS NULL OR Status = 'ERROR' ORDER BY id
      fields: '{
          "ID": "id",
          "NAME": "Name",
          "PRODUCT": "Product",
          "REVISION": "Revision",
          "EDELFLEX": "Codigo Edelflex",
          "PROVEEDOR": "Codigo Proveedor",
          "EQUIPO": "Item_Equipo",
          "MARCA": "Item_Marca",
          "TIPO": "Item_Tipo",
          "DIAMETRO": "Item_Diametro",
          "ESTADO": "Estado_TC"
      }'
      update: UPDATE ${team-center.querys.schema}.dbo.AcceInline SET Status = ?, Fecha_Proceso = ?, Mensaje_Proceso = ?, Id_Proceso = ? WHERE id = ?
    bomba-cen:
      group-code: 1
      get: SELECT FIELDS FROM ${team-center.querys.schema}.dbo.BombaCen WHERE Status IS NULL OR Status = 'ERROR' ORDER BY id
      fields: '{
          "ID": "id",
          "NAME": "Name",
          "PRODUCT": "Product",
          "REVISION": "Revision",
          "EDELFLEX": "Codigo Edelflex",
          "PROVEEDOR": "Codigo Proveedor",
          "MODELO": "Item_Modelo",
          "MARCA": "Item_Marca",
          "TIPO": "Item_Tipo",
          "ESTADO": "Estado_TC"
      }'
      update: UPDATE ${team-center.querys.schema}.dbo.BombaCen SET Status = ?, Fecha_Proceso = ?, Mensaje_Proceso = ?, Id_Proceso = ? WHERE id = ?


batch-process:
  sync-business-partners: 1800000

bitone:
  integration:
    api-key: "d896c408-9f6c-45b7-8ef1-59c323dd67f8"
    url: "http://localhost:8095/services/api/external-batch-process/register"