server:
  port:
    8095
spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    job:
      enabled: false
sap:
  edelflex:
    url: https://10.250.2.10:50000/b1s/v1/
    credentials:
      user: gregorio.hakimian
      password: EDFsapbone
      company: SBOEDEL24TST

sqlserver:
  jdbcUrl: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=master
  username: sa
  password: LongPassword123
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

team-center:
  querys:
    schema: DB_Edelflex_SAP
    get: SELECT FIELDS FROM ${team-center.querys.schema}.dbo.TABLE WHERE Status IS NULL OR Status = 'ERROR' ORDER BY id
    update: UPDATE ${team-center.querys.schema}.dbo.TABLE SET Status = ?, Fecha_Proceso = ?, Mensaje_Proceso = ?, Id_Proceso = ? WHERE id = ?
    configs:
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Codigo Proveedor"
          EQUIPO: "Item_Equipo"
          MARCA: "Item_Marca"
          TIPO: "Item_Tipo"
          DIAMETRO: "Item_Diametro"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          CLAUSE_GROUPITEM: "(CASE WHEN Item_Marca like '%ARAX%' THEN 101 ELSE 102 END)"
        table: "AcceInline"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Codigo Proveedor"
          MODELO: "Item_Modelo"
          MARCA: "Item_Marca"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "BomDesPos"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Codigo Proveedor"
          MODELO: "Item_Modelo"
          MARCA: "Item_Marca"
          TIPO: "Item_Tipo"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "DispLimpi"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Item_Codigo Proveedor"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "ENA"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          FIXED_EDELFLEX: "0303456" #TODO: NO LO ENCONTRE
          PROVEEDOR: "Item_Codigo Proveedor"
          MODELO: "Item_Codigo Proveedor"
          MARCA: "Item_Marca"
          TIPO: "Item_Tipo"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "Homogen"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Codigo Proveedor"
          MODELO: "Item_Modelo"
          MARCA: "Item_Marca"
          TIPO: "Item_Tipo"
          VARIABLE: "Item_Variable"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "InstrInd"
      -
        fields:
          ID: "id"
          NAME: "Name"
          PRODUCT: "Product"
          REVISION: "Revision"
          EDELFLEX: "Codigo Edelflex"
          PROVEEDOR: "Codigo"
          MODELO: "Item_Modelo"
          MARCA: "Item_Marca"
          TIPO: "Item_Tipo"
          VARIABLE: "Item_Variable"
          STATUS: "Estado_TC"
          FIXED_UOM: "UN"
          FIXED_GROUPITEM: 100
        table: "Instrumen"


batch-process:
  sync-business-partners: 1800000

bitone:
  integration:
    api-key: "d896c408-9f6c-45b7-8ef1-59c323dd67f8"
    url: "http://localhost:8095/services/api/external-batch-process/register"