spring:
  data:
    mongodb:
      database: edelflex
      authentication-database: admin
      host: 10.15.0.3
      port: 27017
      username: root
      password: 24z4PmtDgC0Kjpt7cBbK

sqlserver:
  jdbcUrl: jdbc:sqlserver://192.168.54.13:1433;encrypt=true;trustServerCertificate=true;databaseName=master
  username: 4points
  password: ConectorSAP_24
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

team-center:
  querys:
    item-groups:
      acce-inline: 100
      bom-des-pos: 332
      bomba-cen: 305
      disp-limpi: 318
      ena: 310
      homogen: 319
      instr-ind: 307
      instrumen: 307
      inter-calor-kvn: 334
      inter-calor-arax: 308
      mat-pri: 309
      otras-bom: 333
      otras-val: 331
      otros-comp: 306
      pieza: 311
      repuestos: 312
      resto-inter: 304
      semielabo: 320
      sis-cal-eh: 322
      sis-lim-ec: 323
      sis-mez-em: 314
      sis-rec-prod: 324
      sistemas: 335
      subcon: 315
      tanques: 316
      val-ali-seg: 330
      val-asiento: 325
      val-control: 329
      val-dia: 326
      val-fuelle: 327
      val-reten: 328
      valvulas: 317



sap:
  edelflex:
    url: https://10.250.2.10:50000/b1s/v1/
    credentials:
      user: interfaz
      password: qxknQqEU2.
      company: TST_EDELFLEX_AR

# jdbc:sqlserver://;serverName=192.168.54.13;
